<?
namespace Model;
class Session extends Model {
	public static $_schema = array(
		'fields' => array(
			'domain' => array(
				'type' => 'integer',
				'length' => 10,
				'unsigned' => TRUE,
				'not null' => TRUE,
			),
			'user' => array(
				'type' => 'integer',
				'length' => 10,
				'unsigned' => TRUE,
				'not null' => TRUE,
				'description' => 'The user.id corresponding to a session, or 0 for anonymous user.',
			),
			'id' => array(
				'type' => 'string',
				'length' => 32,
				'not null' => TRUE,
				'description' => 'Primary key: A session ID. The value is generated by PHP’s Session API.',
			),
			'timestamp' => array(
				'type' => 'timestamp',
				'length' => 10,
				'unsigned' => TRUE,
				'not null' => TRUE,
				'description' => 'The Unix timestamp when this session last requested a page. Old records are purged by PHP automatically.',
			),
			'data' => array(
				'type' => 'string',
				'length' => 4096,
				'description' => 'The serialized contents of $_SESSION, an array of name/value pairs that persists across page requests by this session ID. Chonoo loads $_SESSION from here at the start of each request and saves it at the end.',
				'default' => NULL,
			),
			'hostname' => array(
				'type' => 'string',
				'length' => 128,
				'not null' => TRUE,
				'description' => 'The IP address that last used this session ID (sid).',
			),
			'userAgent' => array(
				'type' => 'string',
				'length' => 255,
				'not null' => TRUE,
			),
		),
		'indexes' => array(
			'domain' => array('domain', 'user'),
			'timestamp' => array('timestamp'),
		),
		'primary key' => array('domain', 'id'),
	);
}